In [1]:
import pandas as pd
import numpy as np

In [2]:
db_week=pd.read_csv('true_weekly_uploads_umbalanced_data_ada.csv', sep=';')
db_week.head()

,Unnamed: 0,channel,week,first_moderation_update,id_0,type_0,type_10,type_25,False,True,...,category,datetime,subs,treated_0,treated_10,treated_25,treated_ada_0,treated_ada_10,treated_ada_25,date_formated
0,0,UC--24Q3_ZQeFmgJE-Um5QZQ,2016-33,0,1,control,control,control,3,28,...,Travel & Events,2016-08-15 00:00:00,1530.750,0,0,0,1,1,1,2016-08-21
1,1,UC--24Q3_ZQeFmgJE-Um5QZQ,2016-34,0,1,control,control,control,3,28,...,Travel & Events,2016-08-22 00:00:00,1558.625,0,0,0,1,1,1,2016-08-28
2,2,UC--24Q3_ZQeFmgJE-Um5QZQ,2016-35,0,1,control,control,control,3,28,...,Travel & Events,2016-08-29 00:00:00,1591.000,0,0,0,1,1,1,2016-09-04
3,3,UC--24Q3_ZQeFmgJE-Um5QZQ,2016-36,0,1,control,control,control,3,28,...,Travel & Events,2016-09-05 00:00:00,1621.625,0,0,0,1,1,1,2016-09-11
4,4,UC--24Q3_ZQeFmgJE-Um5QZQ,2016-37,0,1,control,control,control,3,28,...,Travel & Events,2016-09-12 00:00:00,1650.750,0,0,0,1,1,1,2016-09-18

In [3]:
db_week.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3267117 entries, 0 to 3267116
Data columns (total 26 columns):
 #   Column                   Dtype
---  ------                   -----
 0   Unnamed: 0               int64
 1   channel                  object
 2   week                     object
 3   first_moderation_update  int64
 4   id_0                     int64
 5   type_0                   object
 6   type_10                  object
 7   type_25                  object
 8   False                    int64
 9   True                     int64
 10  All                      int64
 11  percentage_true          float64
 12  type_channel_0           object
 13  type_channel_10          object
 14  type_channel_25          object
 15  main_cat                 object
 16  category                 object
 17  datetime                 object
 18  subs                     float64
 19  treated_0                int64
 20  treated_10               int64
 21  treated_25               int64
 22  treated_ada_0            int64
 23  treated_ada_10           int64
 24  treated_ada_25           int64
 25  date_formated            object
dtypes: float64(2), int64(12), object(12)
memory usage: 648.1+ MB

In [4]:
db_before=db_week[db_week['first_moderation_update']==0]
db_before

,Unnamed: 0,channel,week,first_moderation_update,id_0,type_0,type_10,type_25,False,True,...,category,datetime,subs,treated_0,treated_10,treated_25,treated_ada_0,treated_ada_10,treated_ada_25,date_formated
0,0,UC--24Q3_ZQeFmgJE-Um5QZQ,2016-33,0,1,control,control,control,3,28,...,Travel & Events,2016-08-15 00:00:00,1530.750000,0,0,0,1,1,1,2016-08-21
1,1,UC--24Q3_ZQeFmgJE-Um5QZQ,2016-34,0,1,control,control,control,3,28,...,Travel & Events,2016-08-22 00:00:00,1558.625000,0,0,0,1,1,1,2016-08-28
2,2,UC--24Q3_ZQeFmgJE-Um5QZQ,2016-35,0,1,control,control,control,3,28,...,Travel & Events,2016-08-29 00:00:00,1591.000000,0,0,0,1,1,1,2016-09-04
3,3,UC--24Q3_ZQeFmgJE-Um5QZQ,2016-36,0,1,control,control,control,3,28,...,Travel & Events,2016-09-05 00:00:00,1621.625000,0,0,0,1,1,1,2016-09-11
4,4,UC--24Q3_ZQeFmgJE-Um5QZQ,2016-37,0,1,control,control,control,3,28,...,Travel & Events,2016-09-12 00:00:00,1650.750000,0,0,0,1,1,1,2016-09-18
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3267080,3267080,UCzzzZ3-icktxbC3j7hkWqRw,2017-07,0,0,treatment,treatment,treatment,0,1,...,Howto & Style,2017-02-12 23:00:00,30222.833333,1,1,1,1,1,1,2017-02-19
3267081,3267081,UCzzzZ3-icktxbC3j7hkWqRw,2017-08,0,0,treatment,treatment,treatment,0,1,...,Howto & Style,2017-02-19 23:00:00,31453.098958,1,1,1,1,1,1,2017-02-26
3267082,3267082,UCzzzZ3-icktxbC3j7hkWqRw,2017-09,0,0,treatment,treatment,treatment,0,1,...,Howto & Style,2017-02-26 23:00:00,32404.369792,1,1,1,1,1,1,2017-03-05
3267083,3267083,UCzzzZ3-icktxbC3j7hkWqRw,2017-10,0,0,treatment,treatment,treatment,0,1,...,Howto & Style,2017-03-05 23:00:00,33465.052083,1,1,1,1,1,1,2017-03-12
3267084,3267084,UCzzzZ3-icktxbC3j7hkWqRw,2017-11,0,0,treatment,treatment,treatment,0,1,...,Howto & Style,2017-03-12 23:00:00,34490.848958,1,1,1,1,1,1,2017-03-19

In [5]:
db_channel_average=db_before.groupby(['channel'],
                           as_index=False, 
                           dropna=False)['subs'].mean().round()

db_channel_average

                        channel     subs
0      UC--24Q3_ZQeFmgJE-Um5QZQ   1873.0
1      UC--2EbuIuBOGgGqPiJxi3rg   4363.0
2      UC--3ozenTzry39-xMqAPQlw  67839.0
3      UC--6E6EpybocdaNlPhvK_9A  31732.0
4      UC--70ql_IxJmhmqXqrkJrWQ  83026.0
...                         ...      ...
51854  UCzzoJY_ln_StRVdrRX1_ftg    357.0
51855  UCzzqd0yx7h1PuC3KJVqeJgw    557.0
51856  UCzzt-UNlRHbEFY3rEpFpuXw  21007.0
51857  UCzzzPMh9fZHxc7gxPRB2LHQ  12932.0
51858  UCzzzZ3-icktxbC3j7hkWqRw  18966.0

[51859 rows x 2 columns]

In [6]:
min_sub=min(db_channel_average['subs'])
max_sub=max(db_channel_average['subs'])

bins=[min_sub,10000, 100000, 1000000, max_sub]
labels=['Less than 10k subs','Between 10k and 100k subs','Between 100k and 1M subs', 'More than 1M subs']
db_channel_average['sub_bin_prior']=pd.cut(x=db_channel_average['subs'], bins=bins, labels=labels, include_lowest=True)
db_channel_average.head()

                    channel     subs              sub_bin_prior
0  UC--24Q3_ZQeFmgJE-Um5QZQ   1873.0         Less than 10k subs
1  UC--2EbuIuBOGgGqPiJxi3rg   4363.0         Less than 10k subs
2  UC--3ozenTzry39-xMqAPQlw  67839.0  Between 10k and 100k subs
3  UC--6E6EpybocdaNlPhvK_9A  31732.0  Between 10k and 100k subs
4  UC--70ql_IxJmhmqXqrkJrWQ  83026.0  Between 10k and 100k subs

In [7]:
db_channel_average.to_csv('channel_average_subs_prior_mod.csv', sep=';')

In [8]:
db_week['channel'].nunique()

51859

In [9]:
db_week=pd.merge(db_week, db_channel_average, how='left', left_on='channel', right_on='channel')
db_week

,Unnamed: 0,channel,week,first_moderation_update,id_0,type_0,type_10,type_25,False,True,...,subs_x,treated_0,treated_10,treated_25,treated_ada_0,treated_ada_10,treated_ada_25,date_formated,subs_y,sub_bin_prior
0,0,UC--24Q3_ZQeFmgJE-Um5QZQ,2016-33,0,1,control,control,control,3,28,...,1530.750,0,0,0,1,1,1,2016-08-21,1873.0,Less than 10k subs
1,1,UC--24Q3_ZQeFmgJE-Um5QZQ,2016-34,0,1,control,control,control,3,28,...,1558.625,0,0,0,1,1,1,2016-08-28,1873.0,Less than 10k subs
2,2,UC--24Q3_ZQeFmgJE-Um5QZQ,2016-35,0,1,control,control,control,3,28,...,1591.000,0,0,0,1,1,1,2016-09-04,1873.0,Less than 10k subs
3,3,UC--24Q3_ZQeFmgJE-Um5QZQ,2016-36,0,1,control,control,control,3,28,...,1621.625,0,0,0,1,1,1,2016-09-11,1873.0,Less than 10k subs
4,4,UC--24Q3_ZQeFmgJE-Um5QZQ,2016-37,0,1,control,control,control,3,28,...,1650.750,0,0,0,1,1,1,2016-09-18,1873.0,Less than 10k subs
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3267112,3267112,UCzzzZ3-icktxbC3j7hkWqRw,2017-39,1,0,treatment,treatment,treatment,0,1,...,53927.000,1,1,1,1,1,1,2017-10-01,18966.0,Between 10k and 100k subs
3267113,3267113,UCzzzZ3-icktxbC3j7hkWqRw,2017-40,1,0,treatment,treatment,treatment,0,1,...,54334.750,1,1,1,1,1,1,2017-10-08,18966.0,Between 10k and 100k subs
3267114,3267114,UCzzzZ3-icktxbC3j7hkWqRw,2017-41,1,0,treatment,treatment,treatment,0,1,...,54783.000,1,1,1,1,1,1,2017-10-15,18966.0,Between 10k and 100k subs
3267115,3267115,UCzzzZ3-icktxbC3j7hkWqRw,2017-42,1,0,treatment,treatment,treatment,0,1,...,55273.625,1,1,1,1,1,1,2017-10-22,18966.0,Between 10k and 100k subs
3267116,3267116,UCzzzZ3-icktxbC3j7hkWqRw,2017-43,1,0,treatment,treatment,treatment,0,1,...,55758.000,1,1,1,1,1,1,2017-10-29,18966.0,Between 10k and 100k subs

In [10]:
db_week.groupby('sub_bin_prior', as_index=False, dropna=False)['channel'].nunique()

C:\Users\mrass\AppData\Local\Temp\ipykernel_9260\2639021673.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  db_week.groupby('sub_bin_prior', as_index=False, dropna=False)['channel'].nunique()

               sub_bin_prior  channel
0         Less than 10k subs    23469
1  Between 10k and 100k subs    20533
2   Between 100k and 1M subs     6777
3          More than 1M subs     1080

In [11]:
db_week.to_csv('true_weekly_uploads_umbalanced_data_ada.csv', sep=';')